version : '3.7'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                # OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-nathan_dev}"
                # HARL_BRANCH: "${HARL_BRANCH:-nathan_dev}"
                GRAPHICS: "${GRAPHICS:-dummy_graphics.js}"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "80:5000"
        
